### PR TITLE
update release notes for 1.4.15 release

### PR DESCRIPTION
**Pull request by dprotaso**

### CODE REVIEW

**Comment by dprotaso** [comment]
Hey @snneji I assigned you since you appear as a contact for the AWS Broker [here](https://docs.google.com/spreadsheets/d/1gZdSo3amQUmIyFSGJfitiyaU5RIAxxgy4gk0E4BXzNs/edit#gid=0)

Either way the release is ready to go on PivNet. Let me know once this appears on the live website and I'll make it public.

thanks,
dave!

**Comment by dprotaso** [comment]
wow that was fast - thanks

**Comment by snneji** [comment]
Thanks @dprotaso, they are in staging at the moments so we'll let you know when they are live.

**Comment by snneji** [comment]
@dprotaso quick question: is "Fixed service plan fields not appearing in OpsManager versions 2.7 and higher" a feature or a bug fix?

**Comment by dprotaso** [comment]
Bug fix

**Comment by snneji** [comment]
The docs are live: http://docs-pcf-staging.cfapps.io/aws-services/release-notes.html

**Comment by dprotaso** [comment]
thanks!

**Pull request merged**
