### PR TITLE
Update release-notes.html.md.erb

### PR DESCRIPTION
**Pull request by dprotaso**

### CODE REVIEW

**Comment by radaeze** [comment]
@dprotaso Thanks for the PR! It has been merged.

**Comment by dprotaso** [comment]
@radaeze thanks for your help

**Comment by aegershman** [comment]
Very minor, but a heads up the index landing page doesn't indicate 1.4.10: https://github.com/pivotal-cf/docs-aws-services/blob/master/index.html.md.erb#L37-L41

I can create a PR for this later if no one else does 👍

**Comment by jncd** [comment]
Thanks @aegershman 
Yes, that's something we check for when we do release notes. (Though, it's always a plus if the release note author makes that change for us too.)
Should be good now, though you might have to hard-refresh your browser.

**Pull request merged**
