### PR TITLE
Updates release notes for v1.4.14

### PR DESCRIPTION
**Pull request by bsnchan**
[#169659719]

### CODE REVIEW

**Comment by snneji** [comment]
Hi @bsnchan, just to let you know we will merge this PR once you get OSL and are ready to release. Before then, I hope you don't mind that we might commits some edits to your PR branch.

**Comment by bsnchan** [comment]
@snneji No problem :)! We actually already have an OSL and are ready to release. The release is marked as "admin only" for now on PivNet and I'm hoping to publish the docs before making the release public.

Thanks!

**Comment by snneji** [comment]
Thanks for letting me know @bsnchan, I'll merge it now. 

Do you plan to release as soon as the docs are live? If so I can edit the PR and publish now and let you know when it's done.

**Comment by bsnchan** [comment]
@snneji yep, I was planning to release as soon as the docs are live. Thanks so much!

**Comment by snneji** [comment]
Hi @bsnchan, the docs are live! https://docs.pivotal.io/aws-services/release-notes.html

**Pull request merged**
