### PR TITLE
1.5

### PR DESCRIPTION
**Pull request by scottgai**
Hi, 

I was told that a PR is needed for reporting doc issue. Please ignore this PR if this is not the right way to do it.
Just found a minor issue with step 7) on this page:
http://docs.pivotal.io/aws-services/installation.html#setup

`7. For each IAM user, click the user name, go to Permissions > Attach Policy, and select PCFInstallationPolicy.`

Actually what I used is the "Add permissions" button. Please verify it. 

Thanks,
Scott

### CODE REVIEW

**Comment by RichardJJG** [comment]
Hi @scottgai, I'm a bit confused by this PR because it concerns your intention to merge 117 commits from 2017/18 into the master branch. Your comment, however, sounds unrelated. Did you mean to create this specific PR for your concern with http://docs.pivotal.io/aws-services/installation.html#setup ?

**Comment by scottgai** [comment]
> Hi @scottgai, I'm a bit confused by this PR because it concerns your intention to merge 117 commits from 2017/18 into the master branch. Your comment, however, sounds unrelated. Did you mean to create this specific PR for your concern with http://docs.pivotal.io/aws-services/installation.html#setup ?

YES, I was told to submit PR for reporting any doc issues. I just want to report a minor issue as I mentioned initially. 
If this is not the right way to report doc issue, please ignore it.

**Comment by RichardJJG** [comment]
> YES, I was told to submit PR for reporting any doc issues. I just want to report a minor issue as I mentioned initially.
> If this is not the right way to report doc issue, please ignore it.

We do like PRs for doc change requests, thanks. I'll see about making your requested change. I was just confused in this case because your PR is somehow attached to many many other commits that aren't related to your concern.

**Comment by Pivotal-Christopher-Wong** [comment]
Hi @scottgai!
I've reviewed the page in question, and have done some revisions to it to update for the changes in AWS's UI. Included in these changes is the issue you mentioned about "Add permissions".

Thank You for bringing this to our attention!

**Pull request closed without merging**
